### ISSUE TITLE
手机端生成的圆圈会超出屏幕导致滚动条的出现

### ISSUE THREAD

**Issue by Maxlife-God** [5ime/Index#3]
如图，圆圈生成后出现了空白区域，尝试使用 overflow: hidden 隐藏多出来的部分，但没有效果。当圆圈被移除后，多出来的部分就会消失。

抱歉，我不是很擅长 js，不知道怎么修复这个问题，如果作者知道且愿意，能否提供一下解决办法

[Screenshot_2023-10-24-20-06-22-926_com.kiwibrowser.browser.jpg](https://github.com/5ime/Index/assets/50244863/a7a19cfb-f8a3-4e82-aa40-6c23ce16ef86)

**Comment by kanodaisuki** [comment]
将HTML的position设置为fixed，可以解决此问题，在[此处](https://github.com/5ime/Index/blob/69768ca0ae4e537e7afeea771f4d3314d0f04ac6/style/css/main.css#L5)添加

**Comment by Maxlife-God** [comment]
> 将HTML的position设置为fixed，可以解决此问题，在[此处](https://github.com/5ime/Index/blob/69768ca0ae4e537e7afeea771f4d3314d0f04ac6/style/css/main.css#L5)添加

十分感谢！原来是通过 css 解决的，之前一直在想怎么改 js
